
package mx.gob.edomex.dgsei.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultaDatosRenapo", targetNamespace = "http://ws.dgsei.edomex.gob.mx/", wsdlLocation = "http://tramitesyservicios.edomex.gob.mx/WebServiceConsultaRenapo/ConsultaDatosRenapo?wsdl")
public class ConsultaDatosRenapo
    extends Service
{

    private final static URL CONSULTADATOSRENAPO_WSDL_LOCATION;
    private final static WebServiceException CONSULTADATOSRENAPO_EXCEPTION;
    private final static QName CONSULTADATOSRENAPO_QNAME = new QName("http://ws.dgsei.edomex.gob.mx/", "ConsultaDatosRenapo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tramitesyservicios.edomex.gob.mx/WebServiceConsultaRenapo/ConsultaDatosRenapo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTADATOSRENAPO_WSDL_LOCATION = url;
        CONSULTADATOSRENAPO_EXCEPTION = e;
    }

    public ConsultaDatosRenapo() {
        super(__getWsdlLocation(), CONSULTADATOSRENAPO_QNAME);
    }

    public ConsultaDatosRenapo(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTADATOSRENAPO_QNAME, features);
    }

    public ConsultaDatosRenapo(URL wsdlLocation) {
        super(wsdlLocation, CONSULTADATOSRENAPO_QNAME);
    }

    public ConsultaDatosRenapo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTADATOSRENAPO_QNAME, features);
    }

    public ConsultaDatosRenapo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaDatosRenapo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaRenapoPorCurp
     */
    @WebEndpoint(name = "ConsultaRenapoPorCurpPort")
    public ConsultaRenapoPorCurp getConsultaRenapoPorCurpPort() {
        return super.getPort(new QName("http://ws.dgsei.edomex.gob.mx/", "ConsultaRenapoPorCurpPort"), ConsultaRenapoPorCurp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaRenapoPorCurp
     */
    @WebEndpoint(name = "ConsultaRenapoPorCurpPort")
    public ConsultaRenapoPorCurp getConsultaRenapoPorCurpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.dgsei.edomex.gob.mx/", "ConsultaRenapoPorCurpPort"), ConsultaRenapoPorCurp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTADATOSRENAPO_EXCEPTION!= null) {
            throw CONSULTADATOSRENAPO_EXCEPTION;
        }
        return CONSULTADATOSRENAPO_WSDL_LOCATION;
    }

}
