
package mx.gob.edomex.dgsei.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaRenapoPorCurp", targetNamespace = "http://ws.dgsei.edomex.gob.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaRenapoPorCurp {


    /**
     * 
     * @param primerApellido
     * @param fechaNacimiento
     * @param entidadFederativa
     * @param segundoApellido
     * @param sexo
     * @param nombre
     * @return
     *     returns mx.gob.edomex.dgsei.ws.PersonasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaPorDetalle", targetNamespace = "http://ws.dgsei.edomex.gob.mx/", className = "mx.gob.edomex.dgsei.ws.ConsultaPorDetalle")
    @ResponseWrapper(localName = "consultaPorDetalleResponse", targetNamespace = "http://ws.dgsei.edomex.gob.mx/", className = "mx.gob.edomex.dgsei.ws.ConsultaPorDetalleResponse")
    @Action(input = "http://ws.dgsei.edomex.gob.mx/ConsultaRenapoPorCurp/consultaPorDetalleRequest", output = "http://ws.dgsei.edomex.gob.mx/ConsultaRenapoPorCurp/consultaPorDetalleResponse")
    public PersonasDTO consultaPorDetalle(
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "primerApellido", targetNamespace = "")
        String primerApellido,
        @WebParam(name = "segundoApellido", targetNamespace = "")
        String segundoApellido,
        @WebParam(name = "fechaNacimiento", targetNamespace = "")
        String fechaNacimiento,
        @WebParam(name = "sexo", targetNamespace = "")
        String sexo,
        @WebParam(name = "entidadFederativa", targetNamespace = "")
        String entidadFederativa);

    /**
     * 
     * @param curp
     * @return
     *     returns mx.gob.edomex.dgsei.ws.PersonasDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaPorCurp", targetNamespace = "http://ws.dgsei.edomex.gob.mx/", className = "mx.gob.edomex.dgsei.ws.ConsultaPorCurp")
    @ResponseWrapper(localName = "consultaPorCurpResponse", targetNamespace = "http://ws.dgsei.edomex.gob.mx/", className = "mx.gob.edomex.dgsei.ws.ConsultaPorCurpResponse")
    @Action(input = "http://ws.dgsei.edomex.gob.mx/ConsultaRenapoPorCurp/consultaPorCurpRequest", output = "http://ws.dgsei.edomex.gob.mx/ConsultaRenapoPorCurp/consultaPorCurpResponse")
    public PersonasDTO consultaPorCurp(
        @WebParam(name = "curp", targetNamespace = "")
        String curp);

}
